name: SQParachute
main: nickmiste.SQParachute
version: 1.0
permissions:
   sqparachute.use:
      description: Allows the player to use parachutes
      default: op
commands:
   parachute:
      description: Change your parachute