name: SQParachute
main: nickmiste.SQParachute
version: 1.0
permissions:
   sqparachute.use:
      description: Allows the player to use parachutes
      default: true
   sqparachute.useglider:
      description: Allows the player to use hang gliders
      default: true
commands:
   parachute:
      description: Change your parachute