name: SQSpaceItems
main: nickmiste.SQSpaceItems
version: 3.0
permissions:
   sqspaceitems.clear:
      description: Allows staff to use /spaceitemsclear
      default: op
commands:
   spaceitemsclear:
      description: Clears all Armor Stands spawned by Space Items
depend: [ProtocolLib]