#This plugin supports dynmap markers. However, only markers for planets that are registered in a 'markers' marker set will be moved.
#Planets are listed in the 'Planets' section below. Example planet given. 
#The name of the planet determines the name of the region, the dynmap marker name, and the name of the planet in movecraft config files
#'RotationStore' points to the Path of the file where the rotation of the planets around their suns are stored and updated.
RotationStoreFile: 'A:/Path/To/The/File/Where/The/Planet/Rotations/Are/Stored.yml'
Planets: 
 Bosquevine: 
   #Floating-points. Coordinates of the sun at the centre of the solar system.
   SunCoords:  
    x: 0.0
    z: 0.0
   #String. Name of the world that the planet structure is in.
   World: "space"
   #Integer. y-level that the (centre of the) planet orbits at. 
   OrbitCenterY: 100
   #Floating-point. Measured in degrees moved round the sun each update. Measured anticlockwise.
   Speed: 5.0
   #Floating-point. Distance of planet from sun in blocks.
   BlocksFromSun: 100.0 
   #Integers. Relative co-ordinates of the corners of the WG region from the planet center.
   RegionMinCornerOffset: 
    x: -1
    y: -1
    z: -1
   RegionMaxCornerOffset: 
    x: 1
    y: 1
    z: 1        
   #String. Path of .schematic file where planet structure is stored
   SchematicPath: 'A:/Path/To/A/File.schematic'
   #List of Strings. Paths of movecraft config files where planet exit data must be placed.
   MovecraftConfigPaths: 
    - 'A:/Path/To/A/Movecraft/Config.yml'
    - 'A:/Second/Path/To/A/Movecraft/Config.yml'