_comment: | 
  This plugin supports dynmap markers. However, only markers for planets that are registered in a 'markers' marker set will be moved.
  Planets are listed below. Example planet given. 
  The name of the planet determines the name of the region, the dynmap marker name, and the name of the planet in movecraft config files
Planets: 
 Bosquevine: 
   _comment: Floating-points. Coordinates of the sun at the centre of the solar system.
   SunCoords:  
    x: 0.0
    z: 0.0
   _comment: String. Name of the world that the planet structure is in.
   World: "space"
   _comment: Integer. y-level that the (centre of the) planet orbits at. 
   OrbitCenterY: 100
   _comment: Floating-point. Measured in degrees moved round the sun each update. Measured anticlockwise.
   Speed: 5.0
   _comment: Floating-point. Distance of planet from sun in blocks.
   BlocksFromSun: 100.0
   _comment: Floating-point. The current anticlockwise rotation of the planet round the sun from its original position, in degrees.
   CurrentAngle: 0.0     
   _comment: Integers. Relative co-ordinates of the corners of the WG region from the planet center.
   RegionMinCornerOffset: 
    x: -1
    y: -1
    z: -1
   RegionMaxCornerOffset: 
    x: 1
    y: 1
    z: 1        
   _comment: String. Path of .schematic file where planet structure is stored
   SchematicPath: 'A:/Path/To/A/File.schematic'
   _comment: List of Strings. Paths of movecraft config files where planet exit data must be placed.
   MovecraftConfigPaths: 
    - 'A:/Path/To/A/Movecraft/Config.yml'
    - 'A:/Second/Path/To/A/Movecraft/Config.yml'